### ISSUE TITLE
RuntimeWarning: invalid value encountered in double_scalars

### ISSUE THREAD

**Issue by egenomics** [wassermanlab/BiasAway#1]
Hi,
I am running BiasAway in a human dataset. tes_background_hsapeins.fa is coming from random fragments of 1000bp (done with bedtools). The TE_set_reference_hg38.fa is a compendium of 4million transposable elements. I get a weird error after quite a while of computation.

time python /home/jl/soft/bias_away/BiasAway.py c -b /projects/TE_stress_project/chip_seq_data/background_seqs/tes_background_hsapiens.fa -f /projects/TE_stress_project/humans/TE_set_reference_hg38.fa -r background_te_hsapiens/ > te_background_gc_matched_hsapiens.fa

/home/jl/soft/bias_away/GC_window_compo_matching.py:37: RuntimeWarning: invalid value encountered in double_scalars
  return gc, min(tmp_gc), max(tmp_gc), sd, 100 * sd / gc
/home/jl/soft/bias_away/GC_window_compo_matching.py:37: RuntimeWarning: divide by zero encountered in double_scalars
  return gc, min(tmp_gc), max(tmp_gc), sd, 100 * sd / gc
Killed

real	726m6.471s
user	704m29.162s
sys	4m44.320s

**Comment by amathelier** [comment]
Should be fixed now.
