### ISSUE TITLE
Assemblies Used for Generating Backgrounds

### ISSUE THREAD

**Issue by imk1** [wassermanlab/BiasAway#3]
Which genome assemblies were used for generating your mouse and human backgrounds?  Thanks!

**Comment by amathelier** [comment]
Thanks for your inquiry. We used mm9 and hg19 at the time. We are updating BiasAway now and provide background sequences for mm10 and hg38; see http://hfaistos.uio.no:8000/ temporarily and https://bitbucket.org/CBGR/biasaway/src/master/.

**Comment by imk1** [comment]
Thank you so much!
