### ISSUE TITLE
hg19 background sequences

### ISSUE THREAD

**Issue by ntoong** [wassermanlab/BiasAway#5]
Hi, do you happen to have hg19 150bp precomputed background sequences? If not, do you have precomputed background sequences of size 150bp? Thank you!

**Comment by amathelier** [comment]
We do no have that unfortunately. I suggest that you look at the most up-to-date BiasAway tool (see https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btaa928/5949736 and https://biasaway.uio.no/). You can generate your own precomputation using our tool at https://bitbucket.org/CBGR/biasaway_background_construction/src/master/. Some precomputed background for hg38 can be found at https://zenodo.org/record/3923866.
